import React, { useState } from 'react';
import { Zap, ShieldCheck, Wrench, BatteryCharging, Home, Lightbulb, Building2, ChevronRight, CheckCircle2 } from 'lucide-react';

interface ServicesProps { onSelectService: (serviceName: string) => void; }

export const Services: React.FC<ServicesProps> = ({ onSelectService }) => {
  const [activeCategory, setActiveCategory] = useState<'all' | 'emergency' | 'residential' | 'panels' | 'commercial'>('all');
  const servicesList = [
    { id:'emergency-outage', category:'emergency', icon:Zap, title:'Emergency Outage & Electrical Repair', badge:'Emergency Service', description:'Sudden blackout, burning electrical smell, sparking outlets, or buzzing breakers? Call Keeton Electric for electrical troubleshooting and repair.', image:'/compassclaw/clients/keeton-electric/hero-bg.jpg', features:['Electrical troubleshooting','Breaker and panel repairs','Outlet and switch repairs','Power restoration'], priceRange:'Call for service' },
    { id:'panel-upgrades', category:'panels', icon:ShieldCheck, title:'Electrical Panel Upgrades', badge:'Panel Service', description:'Electrical panel upgrades for homes and businesses, including modernization and capacity improvements for today’s electrical needs.', image:'/compassclaw/clients/keeton-electric/panel-upgrade.jpg', features:['Panel upgrades','Breaker replacement','Electrical safety improvements','Project estimates'], priceRange:'Call for estimate' },
    { id:'ev-chargers', category:'residential', icon:BatteryCharging, title:'EV Charger Installation', badge:'EV Charger Service', description:'Professional electrical service for EV charger installations and dedicated circuits in homes and other properties.', image:'/compassclaw/clients/keeton-electric/hero-bg.jpg', features:['Level 2 charger service','Dedicated circuits','Garage installations','Electrical load review'], priceRange:'Call for estimate' },
    { id:'ceiling-fans', category:'residential', icon:Home, title:'Ceiling Fan Installation', badge:'Residential Service', description:'Ceiling fan installation and related electrical service for Tacoma-area homes.', image:'/compassclaw/clients/keeton-electric/team-electricians.jpg', features:['New fan installation','Electrical connections','Replacement fans','Residential service'], priceRange:'Call for estimate' },
    { id:'lighting-repair', category:'residential', icon:Lightbulb, title:'Lighting & Electrical Repairs', badge:'Repair Service', description:'Practical electrical repairs for outlets, switches, lighting, thermostats, and other everyday electrical needs.', image:'/compassclaw/clients/keeton-electric/team-electricians.jpg', features:['Outlet and switch repair','Lighting service','Thermostat repair','Electrical troubleshooting'], priceRange:'Call for service' },
    { id:'commercial-electrical', category:'commercial', icon:Building2, title:'Commercial Electrical Service', badge:'Commercial Service', description:'Electrical service for Tacoma-area businesses and commercial properties, from repairs to larger electrical projects.', image:'/compassclaw/clients/keeton-electric/panel-upgrade.jpg', features:['Commercial repairs','Electrical maintenance','Panel service','Project consultations'], priceRange:'Call for estimate' }
  ];
  const filteredServices = activeCategory === 'all' ? servicesList : servicesList.filter(s => s.category === activeCategory);
  return (
    <section id="services" className="py-20 lg:py-28 bg-[#0f172a] relative overflow-hidden">
      <div className="absolute top-1/4 left-0 w-96 h-96 bg-cyan-600/10 rounded-full blur-3xl pointer-events-none"></div><div className="absolute bottom-10 right-0 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none"></div>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <div className="text-center max-w-3xl mx-auto space-y-4"><div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-950/80 border border-cyan-500/30 text-cyan-300 text-xs font-bold uppercase tracking-wider"><Wrench className="w-3.5 h-3.5 text-cyan-400"/><span>What We Do</span></div><h2 className="text-3xl sm:text-4xl lg:text-5xl font-black text-white tracking-tight">Whatever your electrical needs, <span className="electric-gradient-text">we handle it.</span></h2><p className="text-slate-300 text-base sm:text-lg">From electrical repairs and panel upgrades to EV chargers and ceiling fans, Keeton Electric provides practical electrical service for Tacoma-area homes and businesses.</p></div>
        <div className="flex flex-wrap items-center justify-center gap-2 mt-10 mb-12">{[{id:'all',label:'All Services'},{id:'emergency',label:'⚡ Emergency & Repairs'},{id:'panels',label:'🔌 Panel Upgrades'},{id:'residential',label:'🏡 Residential & EV'},{id:'commercial',label:'🏢 Commercial'}].map(tab=><button key={tab.id} onClick={()=>setActiveCategory(tab.id as any)} className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-bold transition-all ${activeCategory===tab.id?'bg-gradient-to-r from-cyan-500 to-blue-600 text-slate-950 shadow-[0_0_15px_rgba(0,210,255,0.3)]':'bg-slate-900/80 text-slate-300 hover:text-white border border-slate-800 hover:border-slate-700'}`}>{tab.label}</button>)}</div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{filteredServices.map(service=>{const Icon=service.icon;return <div key={service.id} className="group bg-slate-900/90 rounded-2xl border border-slate-800 hover:border-cyan-500/50 transition-all duration-300 overflow-hidden flex flex-col justify-between hover:shadow-[0_0_30px_rgba(0,168,255,0.15)]"><div><div className="relative h-48 overflow-hidden"><img src={service.image} alt={service.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"/><div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/40 to-transparent"></div><span className="absolute top-3 left-3 px-3 py-1 rounded-md bg-slate-950/80 border border-cyan-400/40 text-cyan-300 text-xs font-bold backdrop-blur">{service.badge}</span><div className="absolute bottom-3 left-3 p-2.5 rounded-xl bg-cyan-500/90 text-slate-950 shadow-md"><Icon className="w-6 h-6"/></div></div><div className="p-6 space-y-4"><h3 className="text-xl font-bold text-white group-hover:text-cyan-400 transition-colors">{service.title}</h3><p className="text-sm text-slate-300 leading-relaxed">{service.description}</p><ul className="space-y-2 pt-2 border-t border-slate-800/80">{service.features.map((feat,idx)=><li key={idx} className="flex items-start gap-2 text-xs text-slate-300"><CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5"/><span>{feat}</span></li>)}</ul></div></div><div className="p-6 pt-0 border-t border-slate-800/40 flex items-center justify-between mt-4"><div className="text-xs text-slate-400 font-medium"><span className="block text-[10px] text-slate-500 uppercase">Pricing</span>{service.priceRange}</div><button onClick={()=>onSelectService(service.title)} className="px-4 py-2 rounded-lg bg-cyan-500/10 hover:bg-cyan-500 text-cyan-400 hover:text-slate-950 font-bold text-xs border border-cyan-500/30 transition-all flex items-center gap-1.5"><span>Get Quote</span><ChevronRight className="w-3.5 h-3.5"/></button></div></div>})}</div>
        <div className="mt-16 bg-gradient-to-r from-slate-900 via-cyan-950/40 to-slate-900 border border-cyan-500/30 rounded-2xl p-6 sm:p-8 flex flex-col md:flex-row items-center justify-between gap-6"><div className="flex items-center gap-4"><div className="p-4 rounded-2xl bg-cyan-500/20 border border-cyan-400/40 text-cyan-400 shrink-0"><Zap className="w-8 h-8 fill-cyan-400"/></div><div><h4 className="text-lg font-bold text-white">Need something specific or custom electrical work?</h4><p className="text-sm text-slate-300">Keeton Electric provides practical service and project consultations.</p></div></div><a href="tel:+12534483210" className="shrink-0 px-6 py-3.5 rounded-xl bg-gradient-to-r from-cyan-400 to-blue-600 hover:from-cyan-300 hover:to-blue-500 text-slate-950 font-extrabold text-sm shadow-[0_0_20px_rgba(0,210,255,0.3)] transition-all flex items-center gap-2"><span>Speak With Electrician: 253-448-3210</span></a></div>
      </div>
    </section>
  );
};
